AWSTemplateFormatVersion: "2010-09-09"
Description: "VPC Template with IPAM, Multiple Subnets, Route Tables, and IGW"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Naming Convention"
        Parameters:
          - System
          - Environment
      - Label:
          default: "VPC Configuration"
        Parameters:
          - IpamPoolId
      - Label:
          default: "Public Subnet Configuration"
        Parameters:
          - PublicSubnet1Cidr
          - PublicSubnet2Cidr
      - Label:
          default: "Protected Subnet Configuration"
        Parameters:
          - ProtectedSubnet1Cidr
          - ProtectedSubnet2Cidr
      - Label:
          default: "Private Subnet Configuration"
        Parameters:
          - PrivateSubnet1Cidr
          - PrivateSubnet2Cidr
      - Label:
          default: "Transit Gateway Subnet Configuration"
        Parameters:
          - TgwSubnet1Cidr
          - TgwSubnet2Cidr
      - Label:
          default: "Transit Gateway Configuration"
        Parameters:
          - TransitGatewayId
      - Label:
          default: "Route 53 Configuration"
        Parameters:
          - ResolverRuleId
    ParameterLabels:
      System:
        default: "System Name"
      Environment:
        default: "Environment"
      IpamPoolId:
        default: "IPAM Pool ID"
      PublicSubnet1Cidr:
        default: "Public Subnet 1 CIDR"
      PublicSubnet2Cidr:
        default: "Public Subnet 2 CIDR"
      ProtectedSubnet1Cidr:
        default: "Protected Subnet 1 CIDR"
      ProtectedSubnet2Cidr:
        default: "Protected Subnet 2 CIDR"
      PrivateSubnet1Cidr:
        default: "Private Subnet 1 CIDR"
      PrivateSubnet2Cidr:
        default: "Private Subnet 2 CIDR"
      TgwSubnet1Cidr:
        default: "TGW Subnet 1 CIDR"
      TgwSubnet2Cidr:
        default: "TGW Subnet 2 CIDR"
      TransitGatewayId:
        default: "Transit Gateway ID"
      ResolverRuleId:
        default: "Resolver Rule ID"

Parameters:
  System:
    Type: String
    Description: "System name for the naming convention prefix. REQUIRED."
    MinLength: 1
    MaxLength: 50
    AllowedPattern: "^[a-zA-Z0-9-]+$"
    ConstraintDescription: "Must contain only alphanumeric characters and hyphens."

  Environment:
    Type: String
    Description: "Environment for the naming convention prefix. REQUIRED."
    AllowedValues:
      - prod
      - stg
      - dev
    ConstraintDescription: "Must be one of: prod, stg, dev"

  IpamPoolId:
    Type: String
    Description: "IPAM Pool ID for automatic VPC CIDR allocation. REQUIRED."
    AllowedPattern: "^ipam-pool-[0-9a-f]{17}$"
    ConstraintDescription: "Must be a valid IPAM Pool ID (ipam-pool-xxxxxxxxxxxxxxxxx)."

  PublicSubnet1Cidr:
    Type: String
    Description: "CIDR block for Public Subnet 1 (AZ-1). Internet-facing resources. REQUIRED."
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: "Must be a valid IPv4 CIDR block."

  PublicSubnet2Cidr:
    Type: String
    Description: "CIDR block for Public Subnet 2 (AZ-2). Internet-facing resources. REQUIRED."
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: "Must be a valid IPv4 CIDR block."

  ProtectedSubnet1Cidr:
    Type: String
    Description: "CIDR block for Protected Subnet 1 (AZ-1). Resources with outbound internet via TGW. REQUIRED."
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: "Must be a valid IPv4 CIDR block."

  ProtectedSubnet2Cidr:
    Type: String
    Description: "CIDR block for Protected Subnet 2 (AZ-2). Resources with outbound internet via TGW. REQUIRED."
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: "Must be a valid IPv4 CIDR block."

  PrivateSubnet1Cidr:
    Type: String
    Description: "CIDR block for Private Subnet 1 (AZ-1). Internal resources with no direct internet access. REQUIRED."
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: "Must be a valid IPv4 CIDR block."

  PrivateSubnet2Cidr:
    Type: String
    Description: "CIDR block for Private Subnet 2 (AZ-2). Internal resources with no direct internet access. REQUIRED."
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: "Must be a valid IPv4 CIDR block."

  TgwSubnet1Cidr:
    Type: String
    Description: "CIDR block for TGW Subnet 1 (AZ-1). Small subnet for Transit Gateway ENIs. REQUIRED."
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: "Must be a valid IPv4 CIDR block."

  TgwSubnet2Cidr:
    Type: String
    Description: "CIDR block for TGW Subnet 2 (AZ-2). Small subnet for Transit Gateway ENIs. REQUIRED."
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: "Must be a valid IPv4 CIDR block."

  TransitGatewayId:
    Type: String
    Description: "Existing Transit Gateway ID for connectivity. REQUIRED."
    AllowedPattern: "^tgw-[0-9a-f]{17}$"
    ConstraintDescription: "Must be a valid Transit Gateway ID (tgw-xxxxxxxxxxxxxxxxx)."

  ResolverRuleId:
    Type: String
    Description: "Route 53 Resolver Rule ID to attach for DNS resolution. REQUIRED."
    AllowedPattern: "^rslvr-rr-[0-9a-f]{17}$"
    ConstraintDescription: "Must be a valid Resolver Rule ID (rslvr-rr-xxxxxxxxxxxxxxxxx)."

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      Ipv4IpamPoolId: !Ref IpamPoolId
      Ipv4NetmaskLength: 24
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${System}-${Environment}-vpc"

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${System}-${Environment}-igw"

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Public Subnets
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${System}-${Environment}-subnet-public-public-az1"
        - Key: Type
          Value: Public

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${System}-${Environment}-subnet-public-public-az2"
        - Key: Type
          Value: Public

  # Protected Subnets
  ProtectedSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ProtectedSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${System}-${Environment}-subnet-private-protected-az1"
        - Key: Type
          Value: Protected

  ProtectedSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ProtectedSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${System}-${Environment}-subnet-private-protected-az2"
        - Key: Type
          Value: Protected

  # Private Subnets
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${System}-${Environment}-subnet-private-private-az1"
        - Key: Type
          Value: Private

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${System}-${Environment}-subnet-private-private-az2"
        - Key: Type
          Value: Private

  # TGW Subnets
  TgwSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref TgwSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${System}-${Environment}-subnet-private-tgw-az1"
        - Key: Type
          Value: Transit

  TgwSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref TgwSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${System}-${Environment}-subnet-private-tgw-az2"
        - Key: Type
          Value: Transit

  # Route Tables
  # Public Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${System}-${Environment}-rtb-public-public"

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # Protected Route Table
  ProtectedRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${System}-${Environment}-rtb-private-protected"

  ProtectedSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ProtectedSubnet1
      RouteTableId: !Ref ProtectedRouteTable

  ProtectedSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ProtectedSubnet2
      RouteTableId: !Ref ProtectedRouteTable

  # Private Route Table
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${System}-${Environment}-rtb-private-private"

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

  # TGW Route Table
  TgwRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${System}-${Environment}-rtb-private-tgw"

  TgwSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref TgwSubnet1
      RouteTableId: !Ref TgwRouteTable

  TgwSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref TgwSubnet2
      RouteTableId: !Ref TgwRouteTable

  # Routes to Transit Gateway
  ProtectedRouteToTgw:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref ProtectedRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayId: !Ref TransitGatewayId

  PrivateRouteToTgw:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayId: !Ref TransitGatewayId

  TgwRouteToTgw:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref TgwRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayId: !Ref TransitGatewayId

  # Route 53 Resolver Rule Association
  ResolverRuleAssociation:
    Type: AWS::Route53Resolver::ResolverRuleAssociation
    Properties:
      ResolverRuleId: !Ref ResolverRuleId
      VPCId: !Ref VPC

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VPC-ID"

  VpcCidrBlock:
    Description: VPC CIDR Block
    Value: !GetAtt VPC.CidrBlock
    Export:
      Name: !Sub "${AWS::StackName}-VPC-CIDR"

  PublicSubnet1Id:
    Description: Public Subnet 1 ID
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet1-ID"

  PublicSubnet2Id:
    Description: Public Subnet 2 ID
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet2-ID"

  ProtectedSubnet1Id:
    Description: Protected Subnet 1 ID
    Value: !Ref ProtectedSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-ProtectedSubnet1-ID"

  ProtectedSubnet2Id:
    Description: Protected Subnet 2 ID
    Value: !Ref ProtectedSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-ProtectedSubnet2-ID"

  PrivateSubnet1Id:
    Description: Private Subnet 1 ID
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet1-ID"

  PrivateSubnet2Id:
    Description: Private Subnet 2 ID
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet2-ID"

  TgwSubnet1Id:
    Description: TGW Subnet 1 ID
    Value: !Ref TgwSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-TGWSubnet1-ID"

  TgwSubnet2Id:
    Description: TGW Subnet 2 ID
    Value: !Ref TgwSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-TGWSubnet2-ID"

  InternetGatewayId:
    Description: Internet Gateway ID
    Value: !Ref InternetGateway
    Export:
      Name: !Sub "${AWS::StackName}-IGW-ID"
